version: "3.9"

services:
  app:
    container_name: react-app
    build:
      context: .
      dockerfile: infrastructure/docker/app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app                   # Привязка локального исходного кода
      - /app/node_modules            # node_modules остаётся внутри контейнера
    command: ["npm", "start"]
    environment:
      - CHOKIDAR_USEPOLLING=true     # Для отслеживания изменений файлов